### ISSUE TITLE
SyntaxError: Unexpected token *

### ISSUE THREAD

**Issue by siddhudhangar** [orbitdb/orbit-db-docstore#22]
I cloned your orbit-db-docstore git project into my machine. I ran npm install command. i got one error when i ran following code. 
const IPFS = require('ipfs')
const OrbitDB = require('orbit-db')

const ipfs = new IPFS()
const orbitdb = new OrbitDB(ipfs)
const docstore = orbitdb.docstore('db name')

docstore.put({ _id: 'hello world', doc: 'all the things' })
  .then(() => docstore.put({ _id: 'sup world', doc: 'other things' }))
  .then(() => docstore.get('hello'))
  .then((value) => console.log(value))
   [{ _id: 'hello world', doc: 'all the things'}]

/home/glab/my_workspace/orbit-db-docstore/node_modules/pull-stream-to-async-iterator/index.js:4
  return (async function * () {
                         ^

SyntaxError: Unexpected token *
    at new Script (vm.js:51:7)
    at createScript (vm.js:138:10)
    at Object.runInThisContext (vm.js:199:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)

![Screenshot from 2019-03-29 13-01-11](https://user-images.githubusercontent.com/31622143/55219968-2be55800-522c-11e9-9df8-cc790bd8f731.png)

I installed a nodejs which version is v9.5.0 and ipfs into ubuntu machine. kindly check and please let me know.

**Comment by aphelionz** [comment]
Upgrading to node 11 will fix this

**Comment by siddhudhangar** [comment]
I upgraded the node and npm version i.e node version is v10.15.3
 and npm version is 6.0.1. now it is working fine. thanks for your help.
