### ISSUE TITLE
Retrieve docstore values

### ISSUE THREAD

**Issue by sdelvalle57** [orbitdb/orbit-db-docstore#32]
Hey guys.
Im trying to use docstore to save some data, everything works fine when I get to save the data, but when I try to retrieve it I cannot get to achieve it.
This is what Ive done so far:

Saving the object:
```
const assetObject = {
    uid: "12345",
   timestamp: 12345678
}
const orbitdb = await OrbitDB.createInstance(ipfs);
const db = await orbitdb.docstore("my_db", { indexBy: 'uid' })

const insert = await db.put(assetObject);
console.log(insert); //zdpuAkzQ8zUiNNDozukTaStEgqT7pbZaZ25s7w7bAESjSCqHF

const data = await db.get(assetObject.uid);
console.log(data) //data is retrieved without any issue
```

Now from another instance, I try to recover the data:
```
const orbitdb = await OrbitDB.createInstance(ipfs);
const db = await orbitdb.docstore("my_db", { indexBy: 'uid' })
const data = await db.get("12345"); //response is an empty array

//trying another way:
const all = db.query((doc) => doc)
console.log("all", all), //empty array as well
```

Any help please?

Thanks!!

**Comment by shamb0t** [comment]
Hi @sdelvalle57 you need to use the *address* (not just the name) when opening the db on another instance as follows:

```
const orbitdb = await OrbitDB.createInstance(ipfs);
const db = await orbitdb.docstore("my_db", { indexBy: 'uid' })
const address = db.address.toString() 
```
Other instance:
```
const orbitdb = await OrbitDB.createInstance(ipfs);
const db = await orbitdb.docstore(address, { indexBy: 'uid' }) //open here with address
const data = await db.get("12345") // should return data
```
Make sure your ipfs nodes are connected to each other too. Hope that helps!

**Comment by sdelvalle57** [comment]
> 
> 
> Hi @sdelvalle57 you need to use the _address_ (not just the name) when opening the db on another instance as follows:
> 
> ```
> const orbitdb = await OrbitDB.createInstance(ipfs);
> const db = await orbitdb.docstore("my_db", { indexBy: 'uid' })
> const address = db.address.toString() 
> ```
> 
> Other instance:
> 
> ```
> const orbitdb = await OrbitDB.createInstance(ipfs);
> const db = await orbitdb.docstore(address, { indexBy: 'uid' }) //open here with address
> const data = await db.get("12345") // should return data
> ```
> 
> Make sure your ipfs nodes are connected to each other too. Hope that helps!

Thanks, you missed `await db.load()` by the way!

**Comment by RichardLitt** [comment]
@sdelvalle57 Can this be closed?

**Comment by sdelvalle57** [comment]
Sure! Thanks!
