### ISSUE TITLE
Publish 0.2.0 to npm

### ISSUE THREAD

**Issue by haadcode** [orbitdb/orbit-db-docstore#5]
I'm in the process of integrated all orbit-db modules to use the new ipfs-log, merged the updates to master and bumped the version (up 0.2.0 to to match the other orbit-db modules). `npm publish` however stopped me as I don't have access to publish.

@shamb0t I believe, as the original owner of the module, you're the only one with the publishing rights atm. Would you be willing to give me access to publish this module to npm? Or alternatively, publish it yourself? Thank you.

**Comment by shamb0t** [comment]
@haadcode hey sorry missed this msg yesterday! I've published this version and added you as an owner, I think that should give you publishing rights!

**Comment by haadcode** [comment]
Thank you @shamb0t!
