### ISSUE TITLE
Global database identifier

### ISSUE THREAD

**Issue by gaieges** [orbitdb/orbit-db-docstore#7]
Perhaps I'm doing something wrong or don't understand how orbitdb or ipfs fully work, but my understanding around the db / docstore is that it would have a globally unique ID such that it could be referenced by anyone in the network.

So if I was machine A and I created a database, I could move to machine B and open up the same db/docstore by connecting to ipfs and pulling down the initial index that points to all my objects.

Is this the intended behavior? If so, what is that unique identifier?

My current problem is that I can properly store docs in a local docstore, but after restarting the app it seems to forget the entries previously added even after I'm able to confirm the hash can be pulled down from the rest of the network (well, at least my other local node).

**Comment by baimurzin** [comment]
@gaieges Did you solve this problem?

**Comment by gaieges** [comment]
@baimurzin sort of .. I discussed with @haadcode a bit and my general takeaway was 1) this is still very immature, and 2) it works slightly differently than I was expecting.  

I think my main misconception around this was that there would be a permanent filestore index (perhaps provided by ipns?) similar to the way that ipfs files are stored (ie you can pin them), and that the index and data would be of that form (instead the nodes communicate updates via pub sub and they must be connected to each other for those updates to occur).

I haven't had much time to put into this recently so I haven't got anywhere with attempting to improve that.

If @haadcode has any comments here it would be helpful to hear from him directly.  I may be wrong on some of this.

**Comment by haadcode** [comment]
I believe you will find the [latest release](https://github.com/orbitdb/orbit-db) less confusing and buggy as the problems you were experiencing should now be fixed. See [this comment](https://github.com/orbitdb/orbit-db/issues/228#issuecomment-347879705) for details and links.

As for *"Global database identifier"*, see [this comment](https://github.com/orbitdb/orbit-db/issues/224#issuecomment-347878335) for a comprehensive explanation and links to the documentation.

Hopefully the new [getting started guide](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md)  will answer your questions, but if you have more questions or run into problems, feel free to open a new issue! 😄
