### ISSUE TITLE
how orbitdb apply authorization to users?

### ISSUE THREAD

**Issue by jin-cheng-li** [orbitdb/orbit-db-docstore#8]
how to let only  authorized user can access the data store in orbitdb?
does orbitdb has access control?

**Comment by haadcode** [comment]
Thanks for the question @jin-cheng-li and sorry it took a while to get back to you!

We just released a new version [v0.18.0](https://www.npmjs.com/package/orbit-db) that contains write-permissions for the databases. If you need read-access control, you'll have to encrypt the payload on the application side. Read more the [Access Control](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md#access-control) in the new [Getting Started Guide](https://github.com/orbitdb/orbit-db/blob/master/GUIDE.md).

Hope this helps and if you have any further questions, feel free to re-open the issue! 😄
